# Generated by Django 3.2.12 on 2022-02-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_forgetpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgetpassword',
            old_name='user',
            new_name='account',
        ),
    ]
